version: '3'

services:
  neo4j:
    image: neo4j:3.4.5
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH-neo4j/CHANGEME}
      - NEO4J_HOME=/var/lib/neo4j
    ports:
      - 127.0.0.1:7687:7687
      - 127.0.0.1:7474:7474
    volumes:
      - dataVolume:/var/lib/neo4j/data
      - dataVolume:/var/lib/neo4j/logs

  interact-db:
    build: .
    environment:
      - NEO4J_URL=bolt://neo4j
      - NEO4J_AUTH=${NEO4J_AUTH-neo4j/CHANGEME}
    ports:
      - 127.0.0.1:3000:3000
    links:
      - neo4j

volumes:
  dataVolume: {}
