version: '3'

services:
  neo4j:
    image: neo4j:3.4.5
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH-neo4j/CHANGEME}
      - NEO4J_HOME=/var/lib/neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - dataVolume:/var/lib/neo4j/data
      - dataVolume:/var/lib/neo4j/logs

volumes:
  dataVolume: {}
